repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
        files: ^(?!(LICENSE_POOL\.md|LICENSE_POOL\.txt)).*$
      - id: trailing-whitespace
        files: ^(?!(LICENSE_POOL\.md|LICENSE_POOL\.txt)).*$
      - id: mixed-line-ending
        args: [ '--fix=lf' ]
        description: Forces to replace line ending by the UNIX 'lf' character.
        files: ^(?!(LICENSE_POOL\.md|LICENSE_POOL\.txt)).*$
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.2
    hooks:
      - id: ruff
        # fix-only returns 0 if all violations were fixable, else 1
        args: ["--fix-only", "--config=pyproject.toml"]
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        args: ["--config=pyproject.toml"]
  - repo: https://github.com/rhysd/actionlint
    rev: v1.6.27
    hooks:
      - id: actionlint
        args: ["-ignore=.*SC2086", "-ignore=.*SC2002", "-color", ".github/workflows/license-check.yml", ".github/workflows/pre-commit.yml"]
