name: license_check

on:
  schedule:  # first day of the month at 1 pm
    - cron: "0 13 1 * *"
  workflow_dispatch:

jobs:
  license-check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        cache: 'pip'

    - run: python -m pip install -U pip wheel setuptools && python -m pip install licensecheck
    - run: python -m pip freeze --local

    - run: python -m licensecheck
    - run: python -m licensecheck -f simple -o LICENSE_POOL.txt

    # commit and push in case the licenses have changed
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "chore(license_check): Generate dependency licenses"
